1. Create an Array:
Create a 1D NumPy array containing the numbers from 1 to 20.

In [10]:
import numpy as np

np_array = np.arange(1, 21)
print(np_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


2. Reshape the Array:
Reshape the array into a 4x5 2D array.

In [11]:
np_array = np_array.reshape((4, 5))
print(np_array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


3. Array Indexing and Slicing:

Extract the second row from the 2D array.


In [12]:
print(np_array[1])

[ 6  7  8  9 10]


Extract the first two elements of the last row.

In [22]:
print(np_array[3][:2])

[16 17]


Replace all elements in the first column with the value 99.


In [15]:
np_array[0] = 99
print(np_array)

[[99 99 99 99 99]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


Find the sum, mean, and standard deviation of the array.

In [18]:
print(np_array.sum())
print(np_array.mean())
print(np_array.std())

690
34.5
37.426594822398684


Multiply every element in the array by 2.

In [19]:
print(np_array * 2)

[[198 198 198 198 198]
 [ 12  14  16  18  20]
 [ 22  24  26  28  30]
 [ 32  34  36  38  40]]


5. Logical Operations:
Create a boolean mask where elements greater than 10 are True.
Use the mask to extract elements greater than 10.

In [25]:
mask = np_array > 10

print(np_array[mask])

[99 99 99 99 99 11 12 13 14 15 16 17 18 19 20]
