### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [71]:
# 1
import numpy as np

arr = np.random.randint(low=1, high=21, size= (5,5))
arr[:,2] = 1
print(arr)

#2
arr = np.arange(1, 17).reshape((4,4))
np.fill_diagonal(arr, 0)
print(arr)

[[20  5  1 13 18]
 [20  3  1  7  4]
 [18  6  1  3  7]
 [ 2  6  1  7 10]
 [ 3  6  1  3  8]]
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [72]:
# 1
arr = np.arange(1, 37).reshape((6,6))
print(arr[2:5,1:4])

# 2
arr = np.random.randint(low=0, high=100,size=(5,5))
print(arr)
border_elements= np.concatenate((arr[0,:], arr[:,0], arr[-1,:], arr[:,-1]))
print(border_elements)

[[14 15 16]
 [20 21 22]
 [26 27 28]]
[[44 60 94 40  5]
 [95 71 71 33 71]
 [73 63 37 89 50]
 [18 32 14 79  1]
 [ 8 84 36 72 34]]
[44 60 94 40  5 44 95 73 18  8  8 84 36 72 34  5 71 50  1 34]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [73]:
array1 = np.random.randint(low=0, high=100, size=(3,4))
array2 = np.random.randint(low=0, high=100, size=(3,4))

print(array1)
print(array2)

print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)


array = np.arange(1, 17).reshape((4,4))
print(array)
print(array.sum(axis=1))
print(array.sum(axis=0))


[[62 67 74 91]
 [75 25 23 69]
 [73 33  7 71]]
[[37 62 50 40]
 [81 19 92  3]
 [44 89 73 73]]
[[ 99 129 124 131]
 [156  44 115  72]
 [117 122  80 144]]
[[ 25   5  24  51]
 [ -6   6 -69  66]
 [ 29 -56 -66  -2]]
[[2294 4154 3700 3640]
 [6075  475 2116  207]
 [3212 2937  511 5183]]
[[ 1.67567568  1.08064516  1.48        2.275     ]
 [ 0.92592593  1.31578947  0.25       23.        ]
 [ 1.65909091  0.37078652  0.09589041  0.97260274]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[10 26 42 58]
[28 32 36 40]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [74]:
array = np.random.randint(1, 10, size=(5,5))
print(array)
print(f"Mean: {np.mean(array)}")
print(f"Standard Deviation: {np.std(array)}")
print(f"Variance: {np.var(array)}")
print(f"Median: {np.median(array)}")

[[4 1 9 8 9]
 [5 3 3 3 5]
 [8 5 5 4 2]
 [6 5 6 4 6]
 [6 3 8 3 8]]
Mean: 5.16
Standard Deviation: 2.185040045399626
Variance: 4.774400000000001
Median: 5.0


In [75]:
array = np.arange(1, 10).reshape((3,3))
print(array)

array_mean = np.mean(array)
array_std = np.std(array)

normalized_array = (array - array_mean) / array_std
print(normalized_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [76]:
array = np.random.randint(1, 11, size=(3, 3))
row_array = np.random.randint(1, 11, size=(3,))
print("Original array:")
print(array)
print("1D array:")
print(row_array)

print(array + row_array)

# Create a NumPy array of shape (4, 4) filled with random integers
array = np.random.randint(1, 11, size=(4, 4))
column_array = np.random.randint(1, 11, size=(4,))
print("Original array:")
print(array)
print("1D array:")
print(column_array)

# Subtract the 1D array from each column of the 2D array using broadcasting
result = array - column_array[:, np.newaxis]
print("Resulting array:")
print(result)


Original array:
[[5 9 1]
 [5 7 1]
 [1 6 7]]
1D array:
[1 4 7]
[[ 6 13  8]
 [ 6 11  8]
 [ 2 10 14]]
Original array:
[[2 7 5 9]
 [3 7 1 8]
 [4 6 6 3]
 [2 6 9 1]]
1D array:
[8 6 4 4]
Resulting array:
[[-6 -1 -3  1]
 [-3  1 -5  2]
 [ 0  2  2 -1]
 [-2  2  5 -3]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.


In [77]:
array = np.random.randint(1, 11, size = (3,3))
print(array)

print(np.linalg.det(array))

print(np.linalg.eigvals(array))

print(np.linalg.inv(array))

[[ 5  7  8]
 [ 1  5  9]
 [ 4  1 10]]
235.0
[16.12940938+0.j          1.93529531+3.29002909j  1.93529531-3.29002909j]
[[ 0.17446809 -0.26382979  0.09787234]
 [ 0.1106383   0.07659574 -0.15744681]
 [-0.08085106  0.09787234  0.07659574]]


In [78]:
array1 = np.random.randint(1, 11, size = (2, 3))
array2 = np.random.randint(1, 11, size = (3, 2))
print(array1)
print(array2)

result = np.dot(array1, array2)
print("Matrix multiplication result:")
print(result)

[[ 4  9  8]
 [10  5  5]]
[[3 1]
 [2 7]
 [2 3]]
Matrix multiplication result:
[[46 91]
 [50 60]]



### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).


In [ ]:
array = np.random.randint(1, 10, size = (5, 5)).flatten()
print(array)
array = 
print(array)


[8 2 7 9 8 2 6 5 1 4 1 2 6 3 6 3 1 6 5 8 1 3 8 9 7]



### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.



### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.



### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.